### ISSUE TITLE
ftdi_user.sh issue on 64 bit linux

### ISSUE THREAD

**Issue by jackgassett** [GadgetFactory/DesignLab#10]
http://forum.gadgetfactory.net/index.php?/topic/2244-ftdi-usersh-issue-on-kubuntu-64-bits/

**Comment by quicky2000** [comment]
On Kubuntu 64 bits the

apt-get install libftdi-dev

install the 64 bits version of lib ftdi whereas lines 12 and 13 refer to 32 bits version of papilio-prog executable.

By the way execution of papilio-prog failed as it is not able to locate the 32 bits version of libftdi.

By replacing

chgrp dialout hardware/tools/papilio/lin32/papilio-prog
chgrp dialout tools/Papilio_Loader/programmer/linux32/papilio-prog

by

chgrp dialout hardware/tools/papilio/lin64/papilio-prog
chgrp dialout tools/Papilio_Loader/programmer/linux64/papilio-prog

and adding the missing linux64/papilio-prog in tools

cp -rf hardware/tools/papilio/lin64/papilio-prog tools/Papilio_Loader/programmer/linux64

the papilio-prog run properly.

Would it be possible too to avoid the duplication of papilio-prog binaries in two different locations ?

This issue is quite almost the same than #15

**Comment by jackgassett** [comment]
The build.xml file was not properly updating the linux32 binaries to linux64 binaries. This should be fixed now.
