### ISSUE TITLE
Burn of bootloader failed with DesignLab 1.0.3 and DesignLab 1.0.1 on Kubuntu 64 bits

### ISSUE THREAD

**Issue by quicky2000** [GadgetFactory/DesignLab#18]
When trying to restore the AVR bootloader I obtain an error message because file DesignLab-1.0.x/hardware/arduino/avr/bootloaders/caterina/Caterina-Papilio-duo.hex do not exist.

The correct file seems to be DesignLab-1.0.x/hardware/arduino/avr/bootloaders/caterina/Caterina-Papilio-DUO.hex
By creating a symbolic link the burn of bootloader is now successfull

Coudl you perform the necessary corrections in DesignLab so that it searchs the correct name ?

**Comment by jackgassett** [comment]
I actually removed the bootloader entry for the "Papilio DUO - AVR - NO USB - ISP" board type because this board type has fuse settings that prevent the bootloader from loading. It is not valid to load the bootloader with this board type... I'm going to figure out a way to give a nice error message pointing people to the correct board type, "Papilio DUO - AVR - USB".

**Comment by quicky2000** [comment]
Does it mean that it will no more be possible to program avr through FPGA?

**Comment by jackgassett** [comment]
No, you can still do so - you just need to have the "Papilio DUO - AVR - USB" board type selected.
